# Generated by Django 4.0.4 on 2022-05-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut_empleado', models.CharField(max_length=12, verbose_name='RUT')),
                ('Nombre', models.CharField(max_length=100, verbose_name='empleado')),
                ('apaterno', models.CharField(max_length=50, verbose_name='apellido paterno')),
                ('amaterno', models.CharField(max_length=50, verbose_name='apellido materno')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Estado')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de pedido')),
                ('EstadoP', models.CharField(max_length=20, verbose_name='EstadoP')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de producto')),
                ('Nombre_producto', models.CharField(max_length=20, verbose_name='N_producto')),
                ('valor', models.IntegerField(max_length=15, verbose_name='valor')),
                ('cantidad', models.IntegerField(max_length=10, verbose_name='cantidad')),
            ],
        ),
    ]
