# Generated by Django 4.0.4 on 2022-05-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.IntegerField(verbose_name='valor'),
        ),
    ]
