# Generated by Django 4.0.4 on 2022-05-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0002_alter_producto_cantidad_alter_producto_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(max_length=10)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('celular_cliente', models.CharField(max_length=12)),
                ('email_cliente', models.CharField(max_length=50)),
                ('contrasena_cliente', models.CharField(max_length=50)),
                ('confirmar_contrasena_cliente', models.CharField(max_length=50)),
            ],
        ),
    ]
