# Generated by Django 4.0.4 on 2022-05-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0004_alter_cliente_options_alter_cliente_email_cliente_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('rut_cliente', 'celular_cliente', 'email_cliente')},
        ),
    ]
