# Generated by Django 4.0.4 on 2022-05-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0005_alter_cliente_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=200)),
            ],
        ),
    ]
