# Generated by Django 4.0.4 on 2022-05-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0006_imagenes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenes',
            options={'verbose_name': 'Imagenes', 'verbose_name_plural': 'Todas las Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Imagenes', 'verbose_name_plural': 'Todas las Imagenes'},
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='amaterno',
            new_name='apmaterno',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='apaterno',
            new_name='appaterno',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='Rut_empleado',
            new_name='rut_empleado',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='EstadoP',
            new_name='estado_pedido',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Nombre_producto',
            new_name='nombre_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
