# Generated by Django 4.0.4 on 2022-05-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0007_alter_imagenes_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='idEstado',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idpedido',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de pedido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de producto'),
        ),
    ]
