# Generated by Django 4.0.4 on 2022-05-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0008_alter_estado_idestado_alter_pedido_idpedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Productos', 'verbose_name_plural': 'Todos los Productos'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=100, verbose_name='Nombre de producto'),
        ),
    ]
