# Generated by Django 4.0.4 on 2022-06-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0010_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caballos_fuerza',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_motor',
            field=models.CharField(choices=[('0', 'DIESEL'), ('1', 'PETROL'), ('2', 'GAS')], default=1, max_length=1, verbose_name='Tipo de motor'),
            preserve_default=False,
        ),
    ]
