# Generated by Django 4.0.4 on 2022-06-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0011_producto_caballos_fuerza_producto_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_motor',
            field=models.CharField(choices=[('DIESEL', 'DIESEL'), ('PETROL', 'PETROL'), ('GAS', 'GAS')], max_length=10, verbose_name='Tipo de motor'),
        ),
    ]
